import type { Template } from "./types";

export const TEMPLATE_CATEGORIES = [
  "Health",
  "Hygiene",
  "Fitness",
  "Mind",
  "Money",
  "Productivity",
  "Learning",
  "Home",
  "Relationships",
  "Bad Habits",
] as const;

export const TEMPLATES: Template[] = [
  {
    id: "drink-water",
    category: "Health",
    title: "Drink Water",
    emoji: "💧",
    type: "habit",
    color: "#32ADE6",
    unit: "glasses",
    goalValue: 8,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 8,
    notes: "Log a glass each time you drink.",
    endInDays: null,
  },
  {
    id: "sleep",
    category: "Health",
    title: "Sleep 7+ Hours",
    emoji: "🛌",
    type: "average",
    color: "#5856D6",
    unit: "hours",
    goalValue: 7,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "Log hours slept each night.",
    endInDays: null,
  },
  {
    id: "vitamins",
    category: "Health",
    title: "Take Vitamins",
    emoji: "💊",
    type: "habit",
    color: "#FF9500",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "floss",
    category: "Hygiene",
    title: "Floss",
    emoji: "🪥",
    type: "habit",
    color: "#30B0C7",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "shower",
    category: "Hygiene",
    title: "Shower",
    emoji: "🚿",
    type: "habit",
    color: "#32ADE6",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "steps",
    category: "Fitness",
    title: "10k Steps",
    emoji: "🚶",
    type: "average",
    color: "#34C759",
    unit: "steps",
    goalValue: 10000,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "Log daily step count.",
    endInDays: null,
  },
  {
    id: "exercise",
    category: "Fitness",
    title: "Exercise",
    emoji: "💪",
    type: "habit",
    color: "#FF3B30",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [1, 2, 3, 4, 5],
    timesPerPeriod: 5,
    notes: "Move your body.",
    endInDays: null,
  },
  {
    id: "run",
    category: "Fitness",
    title: "Run 100 Miles",
    emoji: "🏃",
    type: "target",
    color: "#FF2D55",
    unit: "miles",
    goalValue: 100,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [1, 3, 5],
    timesPerPeriod: 1,
    notes: "Log miles after each run.",
    endInDays: 90,
  },
  {
    id: "stretch",
    category: "Fitness",
    title: "Stretch",
    emoji: "🧘",
    type: "habit",
    color: "#00C7BE",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "gym",
    category: "Fitness",
    title: "Gym 3x / Week",
    emoji: "🏋️",
    type: "habit",
    color: "#A2845E",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 3,
    notes: "Any 3 days this week.",
    endInDays: null,
  },
  {
    id: "meditate",
    category: "Mind",
    title: "Meditate",
    emoji: "🧘",
    type: "habit",
    color: "#AF52DE",
    unit: "minutes",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "journal",
    category: "Mind",
    title: "Journal",
    emoji: "✍️",
    type: "habit",
    color: "#5856D6",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "gratitude",
    category: "Mind",
    title: "Gratitude",
    emoji: "🙏",
    type: "habit",
    color: "#FFCC00",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "Write three things.",
    endInDays: null,
  },
  {
    id: "no-phone-morning",
    category: "Mind",
    title: "No Phone Morning",
    emoji: "☀️",
    type: "habit",
    color: "#FF9500",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "First 30 minutes phone-free.",
    endInDays: null,
  },
  {
    id: "save",
    category: "Money",
    title: "Save $2,000",
    emoji: "💰",
    type: "target",
    color: "#34C759",
    unit: "$",
    goalValue: 2000,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [5],
    timesPerPeriod: 1,
    notes: "Log deposits toward the goal.",
    endInDays: 120,
  },
  {
    id: "no-spend",
    category: "Money",
    title: "No Spend Day",
    emoji: "🏦",
    type: "habit",
    color: "#0A84FF",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [0, 6],
    timesPerPeriod: 2,
    notes: "",
    endInDays: null,
  },
  {
    id: "track-expenses",
    category: "Money",
    title: "Track Expenses",
    emoji: "🧾",
    type: "habit",
    color: "#FF9500",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "deep-work",
    category: "Productivity",
    title: "Deep Work",
    emoji: "💻",
    type: "habit",
    color: "#0A84FF",
    unit: "hours",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [1, 2, 3, 4, 5],
    timesPerPeriod: 5,
    notes: "One focused block.",
    endInDays: null,
  },
  {
    id: "plan-day",
    category: "Productivity",
    title: "Plan the Day",
    emoji: "📝",
    type: "habit",
    color: "#5856D6",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "inbox-zero",
    category: "Productivity",
    title: "Inbox Zero",
    emoji: "📥",
    type: "habit",
    color: "#30B0C7",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [5],
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "side-project",
    category: "Productivity",
    title: "Launch Side Project",
    emoji: "🚀",
    type: "project",
    color: "#FF2D55",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [6],
    timesPerPeriod: 1,
    notes: "Break the launch into milestones.",
    endInDays: 90,
    milestones: ["Define the idea", "Build MVP", "Get first user", "Public launch"],
  },
  {
    id: "read",
    category: "Learning",
    title: "Read 24 Books",
    emoji: "📚",
    type: "target",
    color: "#AF52DE",
    unit: "books",
    goalValue: 24,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [0],
    timesPerPeriod: 1,
    notes: "Log 1 when you finish a book, or fractions.",
    endInDays: 365,
  },
  {
    id: "read-daily",
    category: "Learning",
    title: "Read 20 Minutes",
    emoji: "📖",
    type: "habit",
    color: "#5856D6",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "language",
    category: "Learning",
    title: "Language Practice",
    emoji: "🗣️",
    type: "habit",
    color: "#32ADE6",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "make-bed",
    category: "Home",
    title: "Make the Bed",
    emoji: "🛏️",
    type: "habit",
    color: "#00C7BE",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "cook",
    category: "Home",
    title: "Cook at Home",
    emoji: "🍳",
    type: "habit",
    color: "#FF9500",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [1, 2, 3, 4, 5],
    timesPerPeriod: 5,
    notes: "",
    endInDays: null,
  },
  {
    id: "tidy",
    category: "Home",
    title: "10-Minute Tidy",
    emoji: "🧹",
    type: "habit",
    color: "#A2845E",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "call-family",
    category: "Relationships",
    title: "Call Family",
    emoji: "📞",
    type: "habit",
    color: "#FF2D55",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [0],
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "date-night",
    category: "Relationships",
    title: "Date Night",
    emoji: "❤️",
    type: "habit",
    color: "#FF3B30",
    unit: "",
    goalValue: 1,
    isBad: false,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: [5, 6],
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "no-sugar",
    category: "Bad Habits",
    title: "No Added Sugar",
    emoji: "🍬",
    type: "habit",
    color: "#FF3B30",
    unit: "",
    goalValue: 0,
    isBad: true,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "Tap Done if you resisted. Log Yes if you had sugar.",
    endInDays: null,
  },
  {
    id: "limit-coffee",
    category: "Bad Habits",
    title: "Limit Coffee",
    emoji: "☕",
    type: "habit",
    color: "#A2845E",
    unit: "cups",
    goalValue: 2,
    isBad: true,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "Log each cup. Limit is 2 per day.",
    endInDays: null,
  },
  {
    id: "no-phone-late",
    category: "Bad Habits",
    title: "No Phone in Bed",
    emoji: "📱",
    type: "habit",
    color: "#5856D6",
    unit: "",
    goalValue: 0,
    isBad: true,
    repeatKind: "daily",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "",
    endInDays: null,
  },
  {
    id: "limit-alcohol",
    category: "Bad Habits",
    title: "Limit Alcohol",
    emoji: "🍷",
    type: "habit",
    color: "#AF52DE",
    unit: "drinks",
    goalValue: 4,
    isBad: true,
    repeatKind: "weekly",
    repeatInterval: 1,
    weekdays: null,
    timesPerPeriod: 1,
    notes: "Weekly max of 4 drinks.",
    endInDays: null,
  },
];

export function templatesByCategory(): { category: string; templates: Template[] }[] {
  return TEMPLATE_CATEGORIES.map((category) => ({
    category,
    templates: TEMPLATES.filter((t) => t.category === category),
  })).filter((group) => group.templates.length);
}
